version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "getrandom"
        # we keep this version of getrandom because uuid locked it as well
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
