mod airac;
mod eurocontrol;
mod faa_arcgis;
mod field15;
mod models;
mod nasr;
mod utils;

use wasm_bindgen::prelude::*;

#[wasm_bindgen(typescript_custom_section)]
const TYPESCRIPT_TYPES: &str = include_str!("../types.d.ts");

pub use airac::{airac_code_from_date, airac_interval, effective_date_from_airac_code};
pub use eurocontrol::EurocontrolResolver;
pub use faa_arcgis::FaaArcgisResolver;
pub use field15::parse_field15;
pub use nasr::NasrResolver;
use utils::set_panic_hook;

#[wasm_bindgen]
pub fn run() -> Result<(), JsValue> {
    set_panic_hook();
    Ok(())
}

#[wasm_bindgen]
pub fn wasm_build_profile() -> String {
    if cfg!(debug_assertions) {
        "debug".to_string()
    } else {
        "release".to_string()
    }
}

#[cfg(all(test, feature = "typescript"))]
mod typescript_tests {
    use super::airac::AiracIntervalRecord;
    use super::faa_arcgis::ArcgisFeatureCollectionInput;
    use super::field15::{ResolvedPoint, RouteSegment};
    use super::models::{
        AirportRecord, AirspaceCompositeRecord, AirspaceLayerRecord, AirwayPointRecord, AirwayRecord, NavpointRecord,
        ProcedureRecord,
    };
    use thrust::data::field15::{Altitude, Connector, Field15Element, Modifier, Point, Speed};
    use ts_rs::{Config, TS};

    const TYPES_PATH: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/types.d.ts");

    fn generate_typescript_types() -> String {
        let config = Config::default();
        let mut out = String::from("// autogenerated. do not edit by hand!!\n\n");

        macro_rules! export_types {
            ($($ty:ty),+ $(,)?) => {
                $(
                    if let Some(docs) = <$ty as TS>::docs() {
                        out.push_str(docs.trim_end());
                        out.push('\n');
                    }
                    out.push_str("export ");
                    out.push_str(&<$ty as TS>::decl(&config));
                    out.push_str("\n\n");
                )+
            };
        }

        export_types!(
            Altitude,
            Speed,
            Modifier,
            Point,
            Connector,
            Field15Element,
            serde_json::Value,
            ArcgisFeatureCollectionInput,
            AirportRecord,
            NavpointRecord,
            AirwayPointRecord,
            AirwayRecord,
            ProcedureRecord,
            AirspaceLayerRecord,
            AirspaceCompositeRecord,
            ResolvedPoint,
            RouteSegment,
            AiracIntervalRecord,
        );

        format!(
            "{}\n",
            out.lines().map(str::trim_end).collect::<Vec<_>>().join("\n").trim_end()
        )
    }

    #[test]
    fn typescript_types_are_current() {
        let committed = std::fs::read_to_string(TYPES_PATH).unwrap();
        assert_eq!(
            committed,
            generate_typescript_types(),
            "run `just types_generate` in crates/thrust-wasm"
        );
    }

    #[test]
    #[ignore = "run with `just types_generate`"]
    fn write_typescript_types() {
        std::fs::write(TYPES_PATH, generate_typescript_types()).unwrap();
    }
}
