_default: pkg

pkg: types_check pkgdir
  @just build_wasm bundler esm
  @just build_wasm web web
  @just build_wasm nodejs nodejs
  @just copy_readme
  @just build_package_json

pkgdir:
  rm -rf pkg
  mkdir -p pkg

build_wasm target outdir:
  wasm-pack build --target {{target}} --release --out-dir pkg/{{outdir}}

copy_readme:
  cp readme.md pkg/README.md

build_package_json:
  jq -s '.[0] * .[1]' pkg/esm/package.json package.json.patch > pkg/package.json

types_check:
  cargo test -p thrust-wasm --features typescript typescript_tests::typescript_types_are_current -- --exact

types_generate:
  cargo test -p thrust-wasm --features typescript typescript_tests::write_typescript_types -- --ignored --exact
