_default: pkg

pkg: pkgdir
  @just build_wasm bundler esm
  @just build_wasm web web
  @just build_wasm nodejs nodejs
  @just copy_readme
  @just build_package_json

pkgdir:
  rm -rf pkg
  mkdir -p pkg

build_wasm target outdir:
  wasm-pack build --target {{target}} --release --out-dir pkg/{{outdir}}

copy_readme:
  cp pkg/esm/README.md pkg/README.md

build_package_json:
  jq -s '.[0] * .[1]' pkg/esm/package.json package.json.patch > pkg/package.json
