// autogenerated. do not edit by hand!!

/**
 * Altitude representation
 */
export type Altitude = { "FL": number } | { "S": number } | { "ft": number } | { "m": number } | "VFR";

/**
 * Speed representation
 */
export type Speed = { "kts": number } | { "Mach": number } | { "km/h": number };

/**
 *  A modifier that changes flight parameters
 */
export type Modifier = {
/**
 * Speed (e.g., "N0456" for 456 knots, "M079" for Mach 0.79, "K0893" for 893 km/h)
 */
speed?: Speed,
/**
 * Flight level or altitude (e.g., "F340" for FL340, "S1130" for 11,300 meters)
 */
altitude?: Altitude,
/**
 * Cruise climb end altitude (for cruise climb)
 */
altitude_cruise_to?: Altitude,
/**
 * Cruise climb indicator (e.g., "PLUS" after speed/altitude)
 */
cruise_climb?: boolean, };

/**
 * A point in the route (waypoint, coordinate, or navaid)
 */
export type Point = { "waypoint": string } | { "coords": [number, number] } | { "point_bearing_distance": {
/**
 * Base point (waypoint or coordinate)
 */
point: Point,
/**
 * Bearing in degrees (000-360)
 */
bearing: number,
/**
 * Distance in nautical miles (001-999)
 */
distance: number, } } | { "aerodrome": string };

/**
 * A connector between points (airway or direct)
 */
export type Connector = { "airway": string } | "DCT" | { "SID": string } | { "STAR": string } | "VFR" | "IFR" | "OAT" | "GAT" | "IFPSTOP" | "IFPSTART" | { "STAY": { minutes?: number, } } | { "NAT": string } | { "PTS": string };

/**
 * A single element in a Field 15 ICAO route
 */
export type Field15Element = Point | Connector | Modifier;

export type JsonValue = number | string | boolean | Array<JsonValue> | { [key in string]: JsonValue } | null;

export type ArcgisFeatureCollectionInput = { features?: Array<JsonValue> | null, };

export type AirportRecord = { code: string, iata?: string, icao?: string, name?: string, latitude: number, longitude: number, region?: string, source: string, };

export type NavpointRecord = { code: string, identifier: string, kind: string, name?: string, latitude: number, longitude: number, description?: string, frequency?: number, point_type?: string, region?: string, source: string, };

export type AirwayPointRecord = { code: string, raw_code: string, kind: string, latitude: number, longitude: number, };

export type AirwayRecord = { name: string, source: string, route_class?: string, points: Array<AirwayPointRecord>, };

export type ProcedureRecord = { name: string, source: string, procedure_kind: string, route_class?: string, airport?: string, points: Array<AirwayPointRecord>, };

export type AirspaceLayerRecord = { lower?: number, upper?: number, coordinates: Array<[number, number]>, };

export type AirspaceCompositeRecord = { designator: string, name?: string, type_?: string, layers: Array<AirspaceLayerRecord>, source: string, };

/**
 * A resolved geographic point in an enriched route.
 */
export type ResolvedPoint = { latitude: number, longitude: number, name?: string, kind?: string, };

/**
 * A resolved route segment (start → end with optional airway name).
 */
export type RouteSegment = { start: ResolvedPoint, end: ResolvedPoint, name?: string, segment_type?: string, connector?: string, };

export type AiracIntervalRecord = { begin: string, end: string, };
